swagger: '2.0'
info:
  version: '1.0.0-beta'
  title: MediaWiki page media API
  description: API for retrieving data about media items appearing on a given page
  termsOfService: https://www.mediawiki.org/wiki/REST_API#Terms_and_conditions
  contact:
    name: Reading Infrastructure
    url: https://www.mediawiki.org/wiki/Wikimedia_Reading_Infrastructure_team
  license:
    name: Apache licence, v2
    url: https://www.apache.org/licenses/LICENSE-2.0
paths:
  /media/{title}{/revision}:
    get:
      tags:
        - Mobile
      summary: Get information on media files used on a page.
      description: |
        Gets the media items (images, audio, and video) in the order in which they appear on a
        given wiki page.

        Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental)
      produces:
        - application/json; charset=utf-8; profile="https://www.mediawiki.org/wiki/Specs/Media/1.0.0"
      parameters:
        - name: title
          in: path
          description: "Page title. Use underscores instead of spaces. Example: `Main_Page`."
          type: string
          required: true
        - name: revision
          in: path
          description: >
            Optional page revision. Note that older revisions are not stored, so
            request latency with the revision would be higher.
          required: false
        - name: redirect
          in: query
          description: >
            Requests for [redirect pages](https://www.mediawiki.org/wiki/Help:Redirects)
            return HTTP 302 with a redirect target in `Location` header and content in the body.

            To get a 200 response instead, supply `false` to the `redirect` parameter.
          type: boolean
          required: false
      responses:
        '200':
          description: JSON containing metadata of media items appearing on the given page.
          schema:
            type: object
          headers:
            ETag:
              description: >
                Syntax: "{revision}/{tid}".
                Example: "701384379/154d7bca-c264-11e5-8c2f-1b51b33b59fc"
        '301':
          description: |
            A permanent redirect is returned if the supplied article title was not in the normalized form.
            To avoid this kind of redirect, you can use the [mediawiki-title](https://github.com/wikimedia/mediawiki-title) library to perform
            title normalization client-side.

            Beware that redirected pre-flighted cross-origin requests (such as those sending custom request headers like `Api-User-Agent`)
            will fail in most current browsers [due to a spec bug](https://github.com/whatwg/fetch/issues/204).
        '302':
          description: |
            The page is a [redirect page](https://www.mediawiki.org/wiki/Help:Redirects).
            The `location` header points to the redirect target.
            If you would like to avoid automatically following redirect pages, set the `redirect=false` query parameter.

            Beware that redirected pre-flighted cross-origin requests (such as those sending custom request headers like `Api-User-Agent`)
            will fail in most current browsers [due to a spec bug](https://github.com/whatwg/fetch/issues/204).
        '404':
          description: Unknown page title
          schema:
            $ref: '#/definitions/problem'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'

      x-request-handler:
        - get_from_pcs:
            request:
              method: get
              headers:
                cache-control: '{{cache-control}}'
              uri: '{{$$.options.host}}/{domain}/v1/page/media/{title}/{revision}'
        - return_to_client:
            return:
              status: 200
              headers: '{{get_from_pcs.headers}}'
              body: '{{get_from_pcs.body}}'

#      x-monitor: true

      x-amples:
        - title: Get media in Foobar page
          request:
            params:
              domain: en.wikipedia.org
              title: Foobar
          response:
            status: 200
            headers:
              content-type: /application\/json/
            body:
              items:
                - titles:
                    canonical: /.+/
                    normalized: /.+/
                    display: /.+/
                  thumbnail:
                    source: /.+/
                    width: /.+/
                    height: /.+/
                    mime: /.+/
                  license:
                    type: /.+/
